# .rubocop.yml
inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-graphql
AllCops:
  NewCops: enable
RSpec/FilePath:
  Enabled: false
Style/Documentation:
  Enabled: false
# Disable the I18nLocaleTexts cop for the entire app
Rails/I18nLocaleTexts:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
    Enabled: false
